# Generated by Django 2.0.9 on 2018-12-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
