# Generated by Django 2.0.9 on 2018-12-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20181231_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='can_id',
            new_name='can_for',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='poll_id',
            new_name='poll_for',
        ),
    ]
