# Generated by Django 2.0.9 on 2019-01-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
